version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - /site:/data/db
    ports:
      - "27017:27017"

  web:
        build: .
        ports:
            - "5000:80"
            - "44348:443"
        depends_on:
            - mongo
        volumes:
            - /.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - /.aspnet/https:/root/.aspnet/https/
        links:
          - mongo
